import type { InboxItem } from "./types";

export const demoItems: InboxItem[] = [
  {
    id: "evt-1042",
    status: "conflict",
    receivedAt: "16:10",
    event: {
      title: "Лабораторная №2 перенесена",
      subject: "Алгоритмы",
      date: "2026-09-20",
      time: "10:10",
      room: "Б-402",
      confidence: 87,
    },
    reason: "Найдены две разные даты. Более позднее сообщение пришло от преподавателя.",
    sources: [
      {
        id: "src-1",
        author: "Анна, староста",
        role: "group-lead",
        kind: "message",
        text: "Лабу по алгоритмам сдаём 18 сентября в 10:10, ауд. Б-402",
        time: "14:32",
        chat: "ИВТ-101 · общий",
      },
      {
        id: "src-2",
        author: "Мария Сергеевна",
        role: "teacher",
        kind: "message",
        text: "Коллеги, лабораторную №2 переносим на 20 сентября. Время и аудитория без изменений.",
        time: "16:10",
        chat: "Алгоритмы · объявления",
      },
    ],
  },
  {
    id: "evt-1041",
    status: "review",
    receivedAt: "15:48",
    event: {
      title: "Консультация перед зачётом",
      subject: "Математика",
      date: "2026-09-17",
      time: "17:30",
      room: "А-218",
      confidence: 72,
    },
    reason: "Дата и время распознаны из голосового сообщения. Нужна быстрая проверка.",
    sources: [
      {
        id: "src-3",
        author: "Илья Воронов",
        role: "student",
        kind: "voice",
        text: "В четверг, семнадцатого, вроде будет консультация в половину шестого в А-218.",
        time: "15:48",
        chat: "ИВТ-101 · общий",
      },
    ],
  },
  {
    id: "evt-1040",
    status: "confirmed",
    receivedAt: "13:05",
    event: {
      title: "Лекция отменена",
      subject: "История",
      date: "2026-09-15",
      time: "12:00",
      room: "Г-105",
      confidence: 96,
    },
    reason: "Сообщение преподавателя подтверждено старостой.",
    sources: [
      {
        id: "src-4",
        author: "Олег Петрович",
        role: "teacher",
        kind: "document",
        text: "Лекция 15 сентября отменяется. Материалы недели приложены к сообщению.",
        time: "12:44",
        chat: "История · материалы",
      },
      {
        id: "src-5",
        author: "Анна, староста",
        role: "group-lead",
        kind: "message",
        text: "Подтверждаю: завтра истории не будет.",
        time: "13:05",
        chat: "ИВТ-101 · общий",
      },
    ],
  },
];
